all:
  hosts:
    er01:
      ansible_connection: network_cli
      ansible_host: 192.168.1.1
      ansible_network_os: edgeos
      wan_interface: "eth0"

      client_private_ip: "192.168.141.2/24"
      server_publickey: "kjsJKhasdiuyIOU823ask2KLJhawd8fy23lkjahdf4E="
      server_public_ip: "34.200.241.65"
      ipsec_psk: "478KJhasdkfjhw8234MNasd"
      ipsec_username: "remoteuser"
      ipsec_user_pass: "2348957KLJhwsmnavergAqiueN"
      client_ip_pool_start: "192.168.140.10"
      client_ip_pool_stop: "192.168.140.200"
      ext_dns1: "1.1.1.1"
      ext_dns2: "208.67.222.222"
      lan_interface1: "eth1"
      cache_size: "4000"
      domain_name: "domain.com"
      network_name: "Home"
      network_subnet1: "192.168.1.0/24"
      device_name1: "er01"
      device_ip1: "192.168.1.1"
      device_mac1: "44:d9:e7:9d:5a:4c"
      ddns_service: "dyndns"
      ddns_host: "subdomain.domain.com"
      ddns_username: "johndoe"
      ddns_passsword: "dnsomaticpassword"