- hosts: er01

  roles:
    # - wireguard_client
    - ipsec_server
    - ad_block
    - dynamic_dns
    - letsencrypt

- hosts: er02

  roles:
    # - wireguard_client
    - ipsec_server
    - ad_block
    - dynamic_dns
    - letsencrypt