- name: configure dynamic dns
  edgeos_config:
    lines:
      - set service dns dynamic interface {{ wan_interface }} service {{ ddns_service }} host-name {{ ddns_host }}
      - set service dns dynamic interface {{ wan_interface }} service {{ ddns_service }} login {{ ddns_username }}
      - set service dns dynamic interface {{ wan_interface }} service {{ ddns_service }} password {{ ddns_password }}
      - set service dns dynamic interface {{ wan_interface }} service {{ ddns_service }} server {{ ddns_provider }}