- name: configure dynamic dns
  edgeos_config:
    lines:
      - set system dns dynamic interface {{ wan_interface }} service {{ ddns_service }} host-name {{ ddns_host }}
      - set system dns dynamic interface {{ wan_interface }} service {{ ddns_service }} login {{ ddns_username }}
      - set system dns dynamic interface {{ wan_interface }} service {{ ddns_service }} password {{ ddns_password }}
      - set system dns dynamic interface {{ wan_interface }} service {{ ddns_service }}  server updates.dnsomatic.com